runtime: go                    # the runtime (python, java, go, php)
api_version: go1               # the runtime version

handlers:
- url: /.*                     # for all requests
  script: _go_app              # pass the request to the Go code

env_variables:
  GOOGLE_CLOUD_PROJECT: "part2-webservice"
  GEOCODE_API_KEY: "put api key here"
